### ISSUE TITLE
AtCoder: can't submit

### ISSUE THREAD

**Issue by ikeji** [nodchip/OnlineJudgeHelper#8]
Steps to reproduce:
1. Run this command with contest, prob and src file name.
```
oj --atcoder $contest $prob
```

Expected:
Submitted the src and open the browser.

Actual:
Get this error
```
Login ... 200
Traceback (most recent call last):
  File "/home/ikeji/tmp/OnlineJudgeHelper/oj.py", line 177, in <module>
    main()
  File "/home/ikeji/tmp/OnlineJudgeHelper/oj.py", line 166, in main
    online_judge.submit()
  File "/home/ikeji/tmp/OnlineJudgeHelper/onlinejudge.py", line 566, in submit
    session = result[0]
IndexError: list index out of range
```
Seems like the script failed to login. (fetched login page instead of submission page.)

**Comment by nodchip** [comment]
Thank you for submitting the issue.  I'm sorry to say this one but this script is almost in maintenance mode.  I will check the issue later.

**Comment by nodchip** [comment]
I migrated the scripts from Python2 to Python3, and fixed some issues.  Could you please try pull the HEAD, and try again?

**Comment by ikeji** [comment]
Thanks for reply.

Sorry I just found this is my configuration problem not script's problem.
I had wrong password on .onlinejudgehelper.setting.json.
Sorry for false alarm.
